modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/MightyDanp/TechAscension/issues"
license="AGPL-3.0 license"

[[mods]]
    modId="techascension"
    logoFile="techascension.png"
    version="0.0.0.1"
    displayName="Tech Ascension"
    displayURL=""
    authors="MightyDanp"
    description='''A simple but powerful coremod.'''

[[dependencies.techascension]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.techascension]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.techascension]]
   modId="techcore"

[[dependencies.techascension]]
   type="required"

[[dependencies.techascension]]
   ordering="NONE"

[[dependencies.techascension]]
   side="BOTH"

[[dependencies.techascension]]
   versionRange="[0.0.0.1,)"

[[mixins]]
   config="techascension.mixins.json"

